"""
Django settings for blog_project project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from datetime import timedelta
import os
from dotenv import load_dotenv

# Load environment variables from .env file
load_dotenv(Path(__file__).resolve().parent.parent.parent / '.env')

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY', 'django-insecure-4=r#=3)9z+sxmn=)*^p%ujw4!%%s)im7rka!w8mu**r(pwa&8r')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG', 'True').lower() == 'true'

ALLOWED_HOSTS = ['127.0.0.1', '0.0.0.0', 'localhost', 'backend', '.netlify.app', '.vercel.app', '.github.io', '.cloudflare.com',"el-deras-writes.onrender.com",
    ".onrender.com", 'testserver']

# Add allowed hosts from environment
if os.environ.get('ALLOWED_HOSTS'):
    additional_hosts = [host.strip() for host in os.environ.get('ALLOWED_HOSTS').split(',')]
    ALLOWED_HOSTS.extend(additional_hosts)

AUTHENTICATION_BACKENDS = [
    'blog.auth_backends.CustomUserBackend',
]

AUTH_USER_MODEL = 'blog.CustomUser'

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes', # Keep contenttypes for PermissionsMixin
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    'blog',
    'rest_framework',
    'rest_framework_simplejwt', # Add this line
    'rest_framework_simplejwt.token_blacklist',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
}


SIMPLE_JWT = {
    # Enhanced token lifetimes for better security
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=15),  # Increased from 5 minutes
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),     # Increased from 1 day
    'ROTATE_REFRESH_TOKENS': True,                   # Enable token rotation for security
    'BLACKLIST_AFTER_ROTATION': True,               # Blacklist old tokens after rotation
    'UPDATE_LAST_LOGIN': False,                      # Disable automatic last_login updates

    # Enhanced security settings
    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,
    'VERIFYING_KEY': None,
    'AUDIENCE': None,
    'ISSUER': 'django-blog-api',                     # Add issuer for token validation
    'JWK_URL': None,
    'LEEWAY': 10,                                    # Allow 10 seconds clock skew

    # Authentication headers
    'AUTH_HEADER_TYPES': ('Bearer',),
    'AUTH_HEADER_NAME': 'HTTP_AUTHORIZATION',
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',
    'USER_AUTHENTICATION_RULE': 'blog.jwt_auth_rules.custom_user_authentication_rule',

    # Token classes and claims
    'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),
    'TOKEN_TYPE_CLAIM': 'token_type',
    'TOKEN_USER_CLASS': 'blog.models.CustomUser',

    # Additional claims
    'JTI_CLAIM': 'jti',
    
    # Custom token claims
    'TOKEN_OBTAIN_SERIALIZER': 'blog.serializers.MyTokenObtainPairSerializer',

    # Sliding token settings (not used but configured)
    'SLIDING_TOKEN_REFRESH_EXP_CLAIM': 'refresh_exp',
    'SLIDING_TOKEN_LIFETIME': timedelta(minutes=15),
    'SLIDING_TOKEN_REFRESH_LIFETIME': timedelta(days=7),
}

CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
    "http://localhost:5173",
    "http://localhost:5174",
    "http://192.168.0.221:5173",
    "https://el-deras-writes.onrender.com",
    "https://elderawrites.netlify.app",
]

# Add CORS origins from environment
if os.environ.get('CORS_ALLOWED_ORIGINS'):
    additional_origins = [origin.strip() for origin in os.environ.get('CORS_ALLOWED_ORIGINS').split(',')]
    CORS_ALLOWED_ORIGINS.extend(additional_origins)

CORS_ALLOWED_ORIGIN_REGEXES = [
    r"^https:\/\/.*\.onrender\.com$",
    r"^https:\/\/.*\.vercel\.app$",
    r"^https:\/\/.*\.netlify\.app$",
    r"^https:\/\/.*\.github\.io$",
    r"^https:\/\/.*\.cloudflare\.com$",
]


ROOT_URLCONF = 'blog_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'blog_project.wsgi.application'


import os
import dj_database_url

# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# PostgreSQL configuration with connection pooling
DATABASES = {
    'default': dj_database_url.config(
        default=os.environ.get('DATABASE_URL', 'postgresql://postgres:postgres@localhost:5432/elderasblog'),
        conn_max_age=600,  # Connection pooling - keep connections alive for 10 minutes
        conn_health_checks=True,  # Enable connection health checks
    )
}

# Fallback to SQLite for development if PostgreSQL is not available
if not os.environ.get('DATABASE_URL'):
    # Use SQLite for local development when no DATABASE_URL is set
    DATABASES['default'] = {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }

# Enhanced database connection pooling settings
DATABASE_CONNECTION_POOLING = {
    'MAX_CONNS': 50,  # Increased for better performance
    'MIN_CONNS': 10,
    'MAX_LIFETIME': 3600,  # Connection lifetime in seconds
    'RETRY_ATTEMPTS': 3,
    'RETRY_DELAY': 1,
}

# Database query optimization settings
DATABASE_QUERY_OPTIMIZATION = {
    'SELECT_RELATED_DEPTH': 2,
    'PREFETCH_RELATED_LOOKUPS': True,
    'USE_PREPARED_STATEMENTS': True,
    'QUERY_TIMEOUT': 30,  # seconds
}

# Performance monitoring settings
PERFORMANCE_MONITORING = {
    'ENABLED': True,
    'SLOW_QUERY_THRESHOLD': 1.0,  # Log queries slower than 1 second
    'TRACK_DB_QUERIES': True,
    'MAX_QUERY_LOG_SIZE': 1000,
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

# AUTH_PASSWORD_VALIDATORS = [
#     {
#         'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
#     },
#     {
#         'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
#     },
#     {
#         'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
#     },
#     {
#         'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
#     },
# ]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# PostgreSQL-specific settings
if 'postgresql' in DATABASES['default']['ENGINE']:
    # Enable PostgreSQL-specific features
    DATABASES['default']['OPTIONS'] = {
        'sslmode': 'prefer',
    }

# Logging configuration for monitoring
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'file': {
            'level': 'INFO',
            'class': 'logging.FileHandler',
            'filename': os.path.join(BASE_DIR, 'logs', 'django.log'),
            'formatter': 'verbose',
        },
        'console': {
            'level': 'DEBUG',
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
        },
    },
    'root': {
        'handlers': ['console', 'file'],
        'level': 'INFO',
    },
    'loggers': {
        'django': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': False,
        },
        'django.db.backends': {
            'handlers': ['console', 'file'],
            'level': 'DEBUG' if DEBUG else 'INFO',
            'propagate': False,
        },
        'blog': {
            'handlers': ['console', 'file'],
            'level': 'DEBUG',
            'propagate': False,
        },
    },
}

# Create logs directory if it doesn't exist
LOGS_DIR = os.path.join(BASE_DIR, 'logs')
os.makedirs(LOGS_DIR, exist_ok=True)

# JWT Security settings
JWT_SECURITY = {
    'MAX_LOGIN_ATTEMPTS': 5,
    'LOGIN_ATTEMPT_TIMEOUT': 3600,  # 1 hour
    'MAX_REQUESTS_PER_HOUR': 1000,
    'TOKEN_BLACKLIST_ENABLED': True,
    'RATE_LIMITING_ENABLED': True,
}

# Media files configuration for image handling
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# File upload settings
FILE_UPLOAD_MAX_MEMORY_SIZE = 5242880  # 5MB
DATA_UPLOAD_MAX_MEMORY_SIZE = 5242880  # 5MB