# Generated by Django 5.2.7 on 2026-01-25 15:47

import blog.utils.uuid_utils
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.UUIDField(default=blog.utils.uuid_utils.uuid7, editable=False, primary_key=True, serialize=False)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('social_media_links', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name': 'Contact Information',
                'verbose_name_plural': 'Contact Information',
                'db_table': 'contact_info',
            },
        ),
        migrations.CreateModel(
            name='VisitorCount',
            fields=[
                ('id', models.UUIDField(default=blog.utils.uuid_utils.uuid7, editable=False, primary_key=True, serialize=False)),
                ('count', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Visitor Count',
                'verbose_name_plural': 'Visitor Counts',
                'db_table': 'visitor_counts',
            },
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.UUIDField(default=blog.utils.uuid_utils.uuid7, editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(db_index=True, max_length=150, unique=True)),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('first_name', models.CharField(blank=True, max_length=30)),
                ('last_name', models.CharField(blank=True, max_length=150)),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('user_type', models.CharField(choices=[('admin', 'Admin'), ('normal', 'Normal')], db_index=True, default='normal', max_length=10)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('is_superuser', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'users',
                'indexes': [models.Index(fields=['email'], name='users_email_idx'), models.Index(fields=['username'], name='users_username_idx'), models.Index(fields=['user_type', 'is_active'], name='users_type_active_idx'), models.Index(fields=['date_joined'], name='users_date_joined_idx')],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=blog.utils.uuid_utils.uuid7, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'db_table': 'categories',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='categories_name_idx')],
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.UUIDField(default=blog.utils.uuid_utils.uuid7, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'db_table': 'feedback',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['created_at'], name='feedback_created_idx'), models.Index(fields=['email'], name='feedback_email_idx')],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.UUIDField(default=blog.utils.uuid_utils.uuid7, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=50, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'db_table': 'tags',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='tags_name_idx'), models.Index(fields=['created_at'], name='tags_created_idx')],
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.UUIDField(default=blog.utils.uuid_utils.uuid7, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(db_index=True, max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('content', models.TextField()),
                ('excerpt', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], db_index=True, default='draft', max_length=10)),
                ('featured', models.BooleanField(db_index=True, default=False)),
                ('views', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.category')),
                ('tags', models.ManyToManyField(blank=True, to='blog.tag')),
            ],
            options={
                'db_table': 'articles',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.UUIDField(default=blog.utils.uuid_utils.uuid7, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(db_index=True, default=django.utils.timezone.now, unique=True)),
                ('count', models.PositiveIntegerField(default=1)),
            ],
            options={
                'db_table': 'visits',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['date'], name='visits_date_idx')],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.UUIDField(default=blog.utils.uuid_utils.uuid7, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('approved', models.BooleanField(db_index=True, default=False)),
                ('is_flagged', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='blog.article')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'comments',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['article', 'approved'], name='comments_article_approved_idx'), models.Index(fields=['author'], name='comments_author_idx'), models.Index(fields=['created_at'], name='comments_created_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['status', 'published_at'], name='articles_status_pub_idx'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['featured', 'status'], name='articles_featured_idx'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['author', 'status'], name='articles_author_idx'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['category'], name='articles_category_idx'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['created_at'], name='articles_created_idx'),
        ),
    ]
