# Generated by Django 5.2.7 on 2026-01-25 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='articles/'),
        ),
        migrations.AddField(
            model_name='article',
            name='readTime',
            field=models.PositiveIntegerField(default=0, help_text='Estimated read time in minutes'),
        ),
    ]
