# Generated by Django 5.2.7 on 2025-12-16 07:16

import django.contrib.postgres.indexes
import django.contrib.postgres.search
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Analytics',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('metric_type', models.CharField(max_length=50)),
                ('metric_value', models.JSONField(default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('referrer', models.URLField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('session_id', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name_plural': 'Analytics',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ArticleRevision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('revision_number', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('excerpt', models.TextField(blank=True, null=True)),
                ('change_summary', models.CharField(blank=True, max_length=500, null=True)),
                ('change_type', models.CharField(default='edit', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('metadata_snapshot', models.JSONField(default=dict)),
            ],
            options={
                'ordering': ['-revision_number'],
            },
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['created_at']},
        ),
        migrations.AddField(
            model_name='article',
            name='authors',
            field=models.ManyToManyField(blank=True, related_name='co_authored_articles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='article',
            name='content_vector',
            field=django.contrib.postgres.search.SearchVectorField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='article',
            name='image_base64',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='read_time',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='scheduled_publish',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='category',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='blog.category'),
        ),
        migrations.AddField(
            model_name='comment',
            name='content_vector',
            field=django.contrib.postgres.search.SearchVectorField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='moderated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='moderated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderated_comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comment',
            name='moderation_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='user_agent',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='avatar_base64',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='location',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='preferences',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='customuser',
            name='timezone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=10),
        ),
        migrations.AddIndex(
            model_name='article',
            index=django.contrib.postgres.indexes.GinIndex(fields=['content_vector'], name='blog_articl_content_f09ee9_gin'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['status', '-published_at'], name='blog_articl_status_47bfec_idx'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['featured', '-created_at'], name='blog_articl_feature_e092d5_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=django.contrib.postgres.indexes.GinIndex(fields=['content_vector'], name='blog_commen_content_8b1342_gin'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['article', 'parent', 'created_at'], name='blog_commen_article_61f536_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['approved', 'is_flagged', 'created_at'], name='blog_commen_approve_17f13e_idx'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=django.contrib.postgres.indexes.GinIndex(fields=['preferences'], name='blog_custom_prefere_b24d85_gin'),
        ),
        migrations.AddField(
            model_name='analytics',
            name='article',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='blog.article'),
        ),
        migrations.AddField(
            model_name='analytics',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='articlerevision',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='blog.article'),
        ),
        migrations.AddField(
            model_name='articlerevision',
            name='changed_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_revisions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='analytics',
            index=models.Index(fields=['metric_type', '-timestamp'], name='blog_analyt_metric__859251_idx'),
        ),
        migrations.AddIndex(
            model_name='analytics',
            index=models.Index(fields=['article', '-timestamp'], name='blog_analyt_article_1d2b8f_idx'),
        ),
        migrations.AddIndex(
            model_name='analytics',
            index=models.Index(fields=['user', '-timestamp'], name='blog_analyt_user_id_0f5a1c_idx'),
        ),
        migrations.AddIndex(
            model_name='analytics',
            index=django.contrib.postgres.indexes.GinIndex(fields=['metric_value'], name='blog_analyt_metric__2c32ca_gin'),
        ),
        migrations.AddIndex(
            model_name='articlerevision',
            index=models.Index(fields=['article', '-revision_number'], name='blog_articl_article_f7c33b_idx'),
        ),
        migrations.AddIndex(
            model_name='articlerevision',
            index=models.Index(fields=['changed_by', '-created_at'], name='blog_articl_changed_f5248f_idx'),
        ),
        migrations.AddIndex(
            model_name='articlerevision',
            index=models.Index(fields=['change_type', '-created_at'], name='blog_articl_change__d3caca_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='articlerevision',
            unique_together={('article', 'revision_number')},
        ),
    ]
