# Generated by Django 5.2.7 on 2025-10-09 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_article_excerpt_article_image_article_readtime'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-created_at']},
        ),
    ]
