# Generated by Django 5.2.7 on 2026-01-25 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_article_image_article_readtime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.URLField(blank=True, help_text='URL to article image', null=True),
        ),
    ]
