# Generated by Django 5.2.7 on 2025-12-17 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_customuser_last_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='moderation_notes',
            field=models.TextField(blank=True, default=''),
        ),
    ]
