# Generated by Django 5.2.7 on 2025-11-09 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_comment_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactinfo',
            name='github_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='linkedin_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='medium_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='pinterest_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='twitter_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='youtube_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
