# Generated by Django 5.2.7 on 2026-01-25 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_comment_parent_comment_comments_parent_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='subject',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
