# Generated by Django 4.2.7 on 2026-01-25 21:59

from django.db import migrations


def ensure_articles_have_categories(apps, schema_editor):
    """Ensure all articles have categories before making the field required"""
    Article = apps.get_model('blog', 'Article')
    Category = apps.get_model('blog', 'Category')
    
    # Create a default category if it doesn't exist
    default_category, created = Category.objects.get_or_create(
        name='General',
        defaults={'description': 'General articles'}
    )
    
    # Update articles without categories
    articles_without_category = Article.objects.filter(category__isnull=True)
    articles_without_category.update(category=default_category)
    
    print(f"Updated {articles_without_category.count()} articles to have the 'General' category")


def reverse_ensure_articles_have_categories(apps, schema_editor):
    """Reverse operation - not needed for this migration"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_feedback_subject'),
    ]

    operations = [
        migrations.RunPython(
            ensure_articles_have_categories,
            reverse_ensure_articles_have_categories
        ),
    ]