# Generated by Django 5.2.7 on 2025-11-09 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_remove_contactinfo_github_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.URLField(blank=True, default='/logo.png', null=True),
        ),
    ]
