# Generated by Django 5.2.7 on 2025-11-15 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_visit_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.TextField(blank=True, default='/logo.png', null=True),
        ),
    ]
