# Generated by Django 5.2.7 on 2025-11-09 01:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_contactinfo_github_link_contactinfo_linkedin_link_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactinfo',
            name='github_link',
        ),
        migrations.RemoveField(
            model_name='contactinfo',
            name='linkedin_link',
        ),
        migrations.RemoveField(
            model_name='contactinfo',
            name='medium_link',
        ),
        migrations.RemoveField(
            model_name='contactinfo',
            name='pinterest_link',
        ),
        migrations.RemoveField(
            model_name='contactinfo',
            name='twitter_link',
        ),
        migrations.RemoveField(
            model_name='contactinfo',
            name='youtube_link',
        ),
    ]
