# Generated by Django 5.2.7 on 2025-11-15 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_tag_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactinfo',
            name='facebook_link',
        ),
        migrations.RemoveField(
            model_name='contactinfo',
            name='instagram_link',
        ),
        migrations.RemoveField(
            model_name='contactinfo',
            name='tiktok_link',
        ),
        migrations.RemoveField(
            model_name='contactinfo',
            name='whatsapp_link',
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='social_media_links',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
